model_params:
  name: 'DIPVAE'
  in_channels: 3
  latent_dim: 10
  lambda_diag: 10 # 0.005
  lambda_offdiag: 1.0 #0.01


exp_params:
  dataset: 2dshapes
  data_path: "data/"
  img_size: 64
  batch_size: 144 # Better to have a square number
  LR: 0.0001
  weight_decay: 0.0
  scheduler_gamma: 0.97

trainer_params:
  gpus: 1
  max_epochs: 50

logging_params:
  save_dir: "logs/"
  name: "DIPVAE"
  manual_seed: 1265
